### PR TITLE
Solve bug of bounty page not showing when refunded

### LINKED ISSUE #757: Staging: error when accessing bounties with refunded deposits
Currently, on staging, I cannot access any of the bounties I created yesterday for which I did at least a refund on one of the deposits. Also, it seems like I get kicked out of the GitHub sign-in when trying to access one of those (when accessing other issues everything looks fine though).

image

### PR DESCRIPTION
**Pull request by ArcAnya**
closes #757 
Related to https://github.com/OpenQDev/OpenQ-Graph/issues/4 as for some reason the staging Subgraph is not showing refund.sender.id

Page should now show normally again and also the content of the refunded:
image

### CODE REVIEW

File: components/Utils/ActionBubble.js [hunk 1]
```diff
@@ -155,9 +156,7 @@ const ActionBubble = ({ addresses, bounty, action }) => {
       <div className='w-full flex-0 rounded-sm overflow-hidden ml-4 border-web-gray border-b before:w-2 before:h-2 before:bg-nav-bg before:absolute before:absolute before:left-12 before:top-[34px] before:border-b  before:border-l before:border-web-gray before:rotate-45  border'>
         <div className={`bg-nav-bg w-full pl-3 ${!action && 'border-web-gray'} flex justify-between`}>
           <span className='py-2'>
-            <span data-testid='actionTitle'>
-              {tokenValues || (!action?.receiveTime && !action?.refundTime) ? titlePartOne : <Skeleton width='34' />}
-            </span>
+            <span data-testid='actionTitle'>{tokenValues || titlePartOne}</span>
```
Comment (Christopher-Stevers) [inline components/Utils/ActionBubble.js]: Token values should not be used as a possible value for this one as its an obj.

File: components/Utils/ActionBubble.js [hunk 2]
```diff
@@ -103,7 +103,8 @@ const ActionBubble = ({ addresses, bounty, action }) => {
   }
 
   if (action?.receiveTime || action?.refundTime) {
-    const funder = senderEnsName || shortenAddress(action.sender.id);
+    const refunder = bounty.deposits.filter((deposit) => deposit.id === action.depositId)[0]?.sender?.id;
+    const funder = senderEnsName || shortenAddress(action.sender?.id) || shortenAddress(refunder);
```
Comment (Christopher-Stevers) [inline components/Utils/ActionBubble.js:107]: Just wondering, why does it have an option to use the refunder address as the funder? Isn't the action.sender.id good enough?

**Review by Christopher-Stevers — CHANGES_REQUESTED** [review]

File: components/Utils/ActionBubble.js (hunk 2 above)
Comment (ArcAnya) [reply components/Utils/ActionBubble.js:107]: action.sender.id was breaking for refunds because it wasn't mapped correctly in the Graph - that's why I used the workaround to get the sender.id for refunds regardless. But this Subgraph PR should fix this: https://github.com/OpenQDev/OpenQ-Graph/pull/5

File: components/Utils/ActionBubble.js (hunk 1 above)
Comment (ArcAnya) [reply components/Utils/ActionBubble.js]: just `{titlePartOne}` then?  
that's the bit I was unsure of, was wondering why there was this conditional initially (`(!action?.receiveTime && !action?.refundTime) ?`)

File: components/Utils/ActionBubble.js (hunk 2 above)
Comment (Christopher-Stevers) [reply components/Utils/ActionBubble.js:107]: Ah, I see

File: components/Utils/ActionBubble.js (hunk 1 above)
Comment (Christopher-Stevers) [reply components/Utils/ActionBubble.js]: Just `titlePartOne`
Not exactly sure. my best guess would be it was  so that the skeleton wouldn't show on minted deposits when the graph hadn't loaded yet. Should be find to remove though.

Comment (ArcAnya) [reply components/Utils/ActionBubble.js]: OK thanks - I've added the change

**Review by Christopher-Stevers — APPROVED** [review]

**Comment by Christopher-Stevers** [comment]
lgtm!
